-- MySQL Script generated by MySQL Workbench
-- dom 06 abr 2014 00:49:32 CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `payit` ;

-- -----------------------------------------------------
-- Table `payit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payit`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `firstname` VARCHAR(99) NOT NULL,
  `lastname` VARCHAR(99) NOT NULL,
  `email` VARCHAR(99) NOT NULL,
  `twitter_access_token` VARCHAR(45) NOT NULL,
  `twitter_access_secret` VARCHAR(45) NOT NULL,
  `twitter_user_id` VARCHAR(45) NOT NULL,
  `twitter_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `payit`.`campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payit`.`campaign` (
  `campaign_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(99) NOT NULL,
  `pretty_url` VARCHAR(15) NOT NULL,
  `description` TEXT NOT NULL,
  `twit` VARCHAR(140) NOT NULL,
  `thank_you` TEXT NOT NULL,
  INDEX `fk_campaign_user_idx` (`user_id` ASC),
  PRIMARY KEY (`campaign_id`),
  UNIQUE INDEX `campaign_id_UNIQUE` (`campaign_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `payit`.`campaign_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payit`.`campaign_has_user` (
  `campaign_has_user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `campaign_id` INT UNSIGNED NOT NULL,
  INDEX `fk_user_campaign_user1_idx` (`user_id` ASC),
  INDEX `fk_user_campaign_campaign1_idx` (`campaign_id` ASC),
  PRIMARY KEY (`campaign_has_user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
